### ISSUE TITLE
Sometimes unexpected behavior of direct peer send

### ISSUE THREAD

**Issue by Strernd** [will123195/p2p-broadcast#2]
Consider the following code
```
const Node = require("p2p-broadcast");

const port = process.env.PORT;

const seedHosts = [];
if (port !== 7000) {
  seedHosts.push(`localhost:7000`);
}

const node = new Node({ port, seedHosts });
const introduce = () => node.broadcast("introduce", { name: port });

node.on("introduce", ({ data, peer }) => {
  console.log(data);
  console.log("sending ack to ", data.name);
  peer.send("ack", { name: port });
});

node.on("ack", ({ data }) => console.log("Got ack from", data.name));

setTimeout(introduce, 2500);
```

and the three nodes A,B,C with port 7000,7001 and 7002
[BASE][/BASE] is same to all 
**Expected Behavior:**
[BASE]
Start A
Start B 2,5s later
B sends introduction
A gets introduction from B
A sending ACK to B
B got ACK from A
Start C (> 2,5s delay)
C sends introducrtion
A gets introduction from C
B gets introduction from C
A sending ACK to C
B sending ACK to C
[/BASE]
C got ACK from A
C got ACK from B

**Sometimes unexpected behavior**
[BASE]
C got ACK from A
A got ACK from B

**or** 

[BASE]
C got ACK from B
B got ACK from A

**Comment by will123195** [comment]
Thanks for reporting, I'll take a look.

**Comment by will123195** [comment]
@Strernd It looks like the issue is the peer is an intermediary, not the original sender. 

For example, I added your "ack" example to the tests:

```
# create mesh network
6001 is connected to: [ 6002, 6003, 6004 ]
6002 is connected to: [ 6001, 6004, 6006 ]
6003 is connected to: [ 6001, 6005, 6006 ]
6004 is connected to: [ 6001, 6002, 6007 ]
6005 is connected to: [ 6003, 6007, 6008 ]
6006 is connected to: [ 6003, 6002, 6008 ]
6007 is connected to: [ 6004, 6005, 6008 ]
6008 is connected to: [ 6006, 6005, 6007 ]
# broadcast message
6001 got ack from 6002
6001 got ack from 6003
6001 got ack from 6004
6002 got ack from 6006  // 6001 <--> 6002 <--> 6006  (6006's peer is 6002, not 6001)
6003 got ack from 6005
6004 got ack from 6007
6006 got ack from 6008
```

**Comment by will123195** [comment]
Currently, I think we're not transmitting the "original sender" in the broadcast. I'd be happy to accept a PR for this!

**Comment by Strernd** [comment]
I completely forgot that the message might not be from the original sender. So the problem is 60 cm in front of the screen here. Sorry for that.

I just did a typescript port of your library in a fork.

**Comment by Strernd** [comment]
Do you have any practical suggestion to establish a P2P channel to every peer and send some messages only to that peer?

**Comment by will123195** [comment]
send only to a specific peer:

```js
node.peers[0].send('hello', data, false)
```
